# Site
name: "Transición energética en México"
title: "Transición energética en México"
description: "Transición energética en México"
meta_description: "Transición energética en México"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'transicionenergeticaenmexico@gmail.com'
#google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Sandra
    display_name: Sandra
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "Activista."
  eluniversal:
    name: Periodico "El Universal"
    display_name: Periodico "El Universal"
    gravatar: 
    email: 
    web: 
    twitter: 
    description: 

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge